name: places
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  fonts:
  - family: Roboto
    fonts:
      - asset: res/fonts/Roboto-Regular.ttf
      - asset: res/fonts/Roboto-Bold.ttf
      - asset: res/fonts/Roboto-Black.ttf
      - asset: res/fonts/Roboto-Light.ttf
      - asset: res/fonts/Roboto-Medium.ttf
      - asset: res/fonts/Roboto-Thin.ttf

      - asset: res/fonts/Roboto-MediumItalic.ttf
      - asset: res/fonts/Roboto-ThinItalic.ttf
        weight: 700

  - family: Roboto
    fonts:
      - asset: res/fonts/Roboto-BlackItalic.ttf
      - asset: res/fonts/Roboto-Italic.ttf
      - asset: res/fonts/Roboto-Light.ttf
      - asset: res/fonts/Roboto-LightItalic.ttf
        style: italic
        weight: 700
